spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  main.allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /accountService
  port: 8080

keycloak:
  enabled: true
  realm: demo
  auth-server-url: http://microservices.demo:30070/auth
#  public-client: true
  resource: account-service
  cors: true
  credentials:
    secret: secret
  bearer-only: true
  ssl-required: external
  security-constraints[0]:
    security-collections[0]:
      name: public endpoints
      patterns[0]: /v1/public/* #public endpoint; no role is associated with it
  security-constraints[1]:
    auth-roles[0]: user #user must have `authenticated-user` role to access the resource
    security-collections[0]:
      name: protected endpoints
      patterns[0]: /* #secure all endpoints by default
#  use-resource-role-mappings: false # this one cannot be true, or this one should be removed!
#  autodetect-bearer-only: true
  principal-attribute: preferred_username