spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
#    time-zone: Asia/Hong_Kong
        
server:
  servlet:
    context-path: /transactionService
  port: 5000
  
logging:
  level:
    org.hibernate.SQL: DEBUG
    
## App Properties
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
