version: "3"
services:
  ms-account:
    # replace username/repo:tag with your name and image details
    image: stephenman/microservices.account:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - kong-net
networks:
  kong-net: